### ISSUE TITLE
BibTeX

### ISSUE THREAD

**Issue by seungwonpark** [gshslatexintro/gshslatexintro#10]
정해진 bst 파일이 필요하다!!

**Comment by LeeJuchan** [comment]
일단 natbib의 newapa 형태가 가장 유사하여 적용시켰습니다.
(mynewapa.bst는 newapa에서 정렬 방법만 논문 참조 순서로 변형시킨 파일입니다.)
newapa는 저자가 일곱을 넘어갈 때에도 ...로 줄여 주지 않는다는 문제점이 있습니다. 그 외에는 URL 표시 등을 제외하면 큰 문제는 없을 것으로 보입니다.

**Comment by LeeJuchan** [comment]
mynewapa.bst 파일을 갱신하여, 저자가 일곱 이상일 때 표준 APA 방식을 따르도록 하였습니다. 만약 오류가 발생한다면 알려주시기 바랍니다.
newapa는 맨 처음 저자의 von part도 lowercase로 씁니다. 이것을 수정할 필요가 있어 보입니다.

**Comment by LeeJuchan** [comment]
mynewapa.bst 파일을 갱신하여, 저자가 일곱 이상일 때 표준 APA 방식을 따르도록 하였습니다. 만약 오류가 발생한다면 알려주시기 바랍니다.

**Comment by seungwonpark** [comment]
신기하네요(?) 

아까 제가 겪었던 문제의 시점에서, bibliographystyle 을 한번 ieeetr 로 바꾼 다음 다시 gshs_thesis 로 되돌려놓고 컴파일하니 잘 돌아갑니다. ㅋㅋㅋㅋㅋ

**Comment by LeeJuchan** [comment]
현재 파일 이름을 gshs_thesis.bst로 변경한 상태입니다.
(혹시나 해서 올린 gshs_thesisnat.bst는 natbib 호환용)
파일을 쓰다가 문제가 되는 상황이 있으면 issue를 다시 열어 문제를 말씀해주시기 바랍니다.
