### ISSUE TITLE
Migration needed?

### ISSUE THREAD

**Issue by seungwonpark** [gshslatexintro/gshslatexintro#11]
현재 gshslatexintro organization 내의 gshslatexintro repository 에 16개의 양식+예시 가 들어있습니다. 그런데 처음 들어와 보는 사람 입장에서는 뭐가 양식이고 뭐가 예시인지 혼동될 수 있고, 방금 @evenharder 님께서 추가해 주신 Manany Harmony Project 와 같은 예시는 어쩔 수 없이 큰 용량을 차지 하게 되는 것 같습니다.

따라서, 이 organization 안에 'example' repository 를 만들어서 예시 tex 프로젝트들을 옮기고자 하는데, 이에 대해 어떻게 생각하는지 의견을 여쭤보고자 합니다.

**Comment by seungwonpark** [comment]
양식 파일들 : (8개, 약 2MB)
GSHS RnE report class(기초,심화 알앤이)
gshs_chem_experiment
gshs_reading
gshs_thesis_certified(졸업논문양식,공식)
gshs_thesis_certified-adv
gshs_thesis_sample-report(졸업논문)
Humantech_Paper_Award
Jointed_RnE_presentation

예시 파일들 : (8개, 약 8MB, 용량 최소화를 위해 많은 이미지 첨부를 포기했던 상태)
2015_Science_Research_Writing
2016_GSHS_Linear_Algebra_midterm
Advanced_Physics_14041
Calculus_Prob_14041
Discrete_Data_Prob_14080
Korean_and_Life_14041
Manany_Harmony_Project
sample_document

**Comment by LeeJuchan** [comment]
좋은 의견 같습니다. 양식과 문서의 구분은 필요하다고 봅니다.
gshs_chem_experiment 같은 폴더는 양식과 예시 문서가 같이 들어 있는 형태이므로, 졸업논문 양식과 같이 작성 요령이 내용인 파일을 하나 만들 필요가 있어 보입니다.

**Comment by evenharder** [comment]
(얼추) 완성된 프로젝트 파일들과 양식 파일들을 구분짓는 건 필요한 것 같네요. 동의합니다.

**Comment by seungwonpark** [comment]
좋습니다. 그러면 예시 파일들을 새로운 repository로 옮기도록 하겠습니다.

**Comment by seungwonpark** [comment]
Migration done.

https://github.com/gshslatexintro/gshslatexintro/commit/d6fcecc73f415eb54361f99076cf5d858e80b7c3

https://github.com/gshslatexintro/examples/commit/e87a958bd80a8aaa5e338364d84c11189a227f4a
