### ISSUE TITLE
'-' 여러번 써서 긴 대시를 만들 수 없음

### ISSUE THREAD

**Issue by jmpasta** [gshslatexintro/gshslatexintro#13]
cls 파일
\setmainfont{Times New Roman} 를 
\setmainfont[Ligatures=TeX]{Times New Roman} 로 고치지 않으면
자간이 망해서 --- 가 붙지 않고 떨어져 보임.

**Comment by seungwonpark** [comment]
오오 :+1: 
그러니까 초대 좀 받으셔서 들어오고 코드 고치세요 ㅋㅋ
아니면 이 내용 적용한 pull request 하셔도 되고...

**Comment by seungwonpark** [comment]
그런데 긴 대시 만들 일이 있나요...?

**Comment by LeeJuchan** [comment]
cls 파일을 수정하여 en-dash 등이 떨어져 보이지 않도록 수정하였습니다.
제 경우는 정상적으로 보여 그렇게 되는 줄 몰랐습니다. 아마 LaTeX version 문제 아닐까 싶습니다.

**Comment by seungwonpark** [comment]
추가 설명 : 긴 대시는 참고 문헌 인용시 3--5 이렇게 사용되는 경우가 있다.
