### ISSUE TITLE
독서 독후감 양식 문제점

### ISSUE THREAD

**Issue by seungwonpark** [gshslatexintro/gshslatexintro#14]
독서 독후감 양식을 사용하는 데 다음 문제점들이 발견되었습니다.
- 따옴표가 평소와 다르게 출력됨. 그래서 ' 만 사용중
- footnote 를 사용하면 에러 발생. 가령 \footnote{asdf} 라고 입력했을 때

`Missing number, treated as zero. ^^\footnote{asdf}`
`Illegal unit of measure (pt inserted). ^^\footnote{asdf}`

**Comment by LeeJuchan** [comment]
(TeXLive 2015 환경에서 시험하였습니다.)
따옴표와 footnote 모두 정상적으로 출력됨을 확인하였습니다.
따옴표 문제는 지난 issue #13 과 동일한 문제로 보입니다. 비슷한 방식으로 해결 가능해 보입니다.
Footnote 문제의 경우, 문제를 확인하지 못했습니다. 컴파일 환경과 상황에 관한 구체적인 코드를 올려 주시면 문제 파악에 도움이 될 것 같습니다.

**Comment by LeeJuchan** [comment]
Footnote 관련해서, 동일한 문제가 생기는 것을 확인하였습니다. 원인 파악 중에 있습니다.

**Comment by LeeJuchan** [comment]
\SetHangulspace 명령의 두 번째 인자 값이 비어 있어 발생하는 문제였습니다. 문제를 해결한 코드를 업데이트하였습니다.

**Comment by LeeJuchan** [comment]
현재 TeXLive 2015 환경에서는 따옴표, dash 등의 모양이 바뀌어 나오는 문제를 확인할 방법이 없습니다.
혹시 @seungwonpark 분과 같은 문제가 발생하시는 분은, 우선 다음의 코드를 삽입하여 증상이 해결되는지 확인해 주신 뒤 알려주시기 바랍니다.
`\usepackage{fontspec}
\defaultfontfeatures{Ligatures=TeX}`
문제가 해결된다면 이 코드를 .cls 파일에 추가하겠습니다.
만약 이를 통해 문제가 해결되지 않는다면 이전 #13 의 해결 방법을 .cls 파일에 적용하겠습니다.

**Comment by seungwonpark** [comment]
TeXLive 2013 환경에서 시험해본 결과, 
`\usepackage{fontspec} \defaultfontfeatures{Ligatures=TeX}`
로는 해결되지 않고, #13 의 방법을 적용하니 해결되었습니다.

**Comment by seungwonpark** [comment]
편집 충돌을 막기 위해 제가 적용하지는 않겠습니다.

**Comment by LeeJuchan** [comment]
Ligatures=TeX 옵션을 .cls 파일에 적용하였습니다. 확인 후 문제가 해결되었다면 issue를 닫아 주시기 바랍니다.

**Comment by seungwonpark** [comment]
해결되었습니다.
