### ISSUE TITLE
XeLaTeX compilation file name

### ISSUE THREAD

**Issue by seungwonpark** [gshslatexintro/gshslatexintro#15]
(독서 독후감 양식으로 시험해 보았습니다.)

XeLaTeX 으로 컴파일하는데, 파일 이름에 한글이 포함되어 있으면 컴파일이 되지 않습니다.

결과 pdf 파일의 이름을 나중에 수정해 주는 것밖에 해결책이 없을까요...

**Comment by LeeJuchan** [comment]
현재 XeLaTeX은 Linux 환경에서는 파일 이름을 UTF-8로 제대로 전달하나, Windows 환경에서는 파일 이름을 ANSI로 전달하기 때문에 한글이 포함되어 있으면 컴파일이 되지 않습니다. 이 점은 양식 문제가 아니라, 엔진 자체 문제이므로 본 양식에서 해결하기 어렵습니다. 문서의 구분을 위해서는 하나의 문서를 하나의 폴더에 넣고 폴더명으로 구분하는 것이 적당할 것입니다.
