### ISSUE TITLE
기초, 심화 R&E 양식 관련 제안

### ISSUE THREAD

**Issue by LeeJuchan** [gshslatexintro/gshslatexintro#16]
현재 클래스 버전이 클래스명에 반영되고 있는데, 이렇게 되면 새 클래스가 나올 때마다 이전에 작성한 문서의 불러온 클래스 이름을 바꾸어 주어야 하는 문제가 생깁니다. 
\ProvidesClass{gshs-report-v1.21}의 형식을
\ProvidesClass{gshs-report}[2016/06/10 v.1.21]와 같이 바꾸는 것은 어떨까요?
그리고 양식의 모든 코드가 text로 작성되어 quote로 묶여 있는 형식인데, 이를 verbatim 환경으로 바꾸는 것이 더 좋을 것 같습니다. 읽는 사람과 양식을 유지·보수하는 쪽 모두가 편할 것 같습니다.

**Comment by seungwonpark** [comment]
사실 클래스명이 바뀌는 (저의) 기준은, 새로운 명령어가 생겨나서(얼마 전의 v1.2의 경우는 advisoremail이라든지) 클래스 파일을 수정할 때 tex 파일도 추가 수정이 필요할 경우였습니다. 때문에 이번 v1.21은 클래스명이 바뀔 필요가 없어 보입니다. 다시 말해, 사용자들이 클래스명이 변경됨을 보고 나서 'tex파일도 수정이 필요하구나'를 알 수 있게 하기 위해 클래스명을 변경하고 있었습니다. tex파일도 수정이 필요할 정도의 cls파일 수정은 "중대한 수정" 으로 취급한 것이죠. (이해가 잘 안되시면 재질문해주시기 바랍니다. 필력이 부족해서...)

하지만, 이젠 추가로 명령어를 생성할 일이 없어 보이니 제안하신 대로 하셔도 좋을 것 같습니다. 대신 사용자들이 헷갈릴 수 있으니 {gshs-report-v1.2}[2016/06/10 v 1.21] 과 같이 하는 것은 어떨지요? 페이스북으로 공지하면서도 이미 v1.2를 붙여버리기도 하였고요.
- quote 대신 verbatim을 사용하는 것이 좋아 보입니다. 수고해 주셔서 감사합니다.

**Comment by LeeJuchan** [comment]
일단 공지가 된 상황이므로 파일과 클래스 이름은 그대로 두는 것이 좋겠습니다. 동의합니다.
중간보고서 제출이 끝난 이후 수정하는 쪽으로 하는 것이 좋을 것 같습니다.

**Comment by LeeJuchan** [comment]
v1.21 파일을 v1.2로 바꾸었습니다.

**Comment by seungwonpark** [comment]
문제가 모두 해결되었나요?
