### ISSUE TITLE
졸업논문 TeX 양식 확정 관련 논의

### ISSUE THREAD

**Issue by LeeJuchan** [gshslatexintro/gshslatexintro#19]
경기과학고 TeX 사용자협회의 규범에 따라, 2016학년도 3학년 학생들은 조금 있으면 owner 권한을 해제하고 member로 참여하게 됩니다. 그런데 그렇게 되면 파일을 직접 수정하는 것이 어려워지는 문제가 있을 것 같아, 그 전까지 졸업논문 양식의 수정을 마무리하고 2016학년도 졸업논문의 TeX 양식을 확정하는 절차가 필요할 것 같습니다. 이에 2월 2일까지 수정이 이루어진 뒤 수정을 마감하고자 합니다. (설 연휴로 인하여 1월 중으로는 무리일 것 같습니다.) 혹시 아직 양식의 수정이 더 필요한 부분이 있다고 생각하시는 분들은 의견 부탁드리겠습니다.
2017학년도 졸업논문 양식이 아직 공고되지 않아 양식이 바뀔 수도 있기는 하지만, 2016학년도와 같이 전 년도와 양식이 동일하다면 지금 확정한 양식이 그대로 사용될 수 있을 것으로 보입니다. 2017학년도에는 파편화된 양식이 아닌 하나의 통일된 양식으로 졸업논문을 작성하여, 혹여나 양식의 수정이 필요할 때에도 .cls 파일 등의 간단한 수정만으로 일괄적인 수정을 할 수 있는 환경이 마련되었으면 좋겠습니다.

**Comment by seungwonpark** [comment]
> 2017학년도에는 파편화된 양식이 아닌 하나의 통일된 양식으로 졸업논문을 작성하여, 혹여나 양식의 수정이 필요할 때에도 .cls 파일 등의 간단한 수정만으로 일괄적인 수정을 할 수 있는 환경이 마련되었으면 좋겠습니다.

혹시 `gshs_thesis`와 `gshs_thesis-adv`를 하나로 통일하자는 말씀이신가요?

**Comment by LeeJuchan** [comment]
하나로 통일할 필요까지는 없고, 각 repository의 이름을 gshs_thesis_2015, gshs_thesis_2016 정도로 변경하여 legacy의 형태로 남기는 것이 어떨까 합니다.
2016학년도에는 졸업논문을 TeX으로 쓰는 학생들이 여러 개의 서로 다른 양식을 사용하는 경우가 있었고, 그래서 일일히 수정 사항을 알려 주어야 하는 문제가 있었기 때문에 통일된 양식의 사용이 필요하다는 것을 말한 것입니다.
가급적 2017학년도에는 지금 확정한 판본이 그대로 사용될 수 있었으면 합니다만, 양식이 수정되면 어떻게 될 지 모르겠네요.

**Comment by seungwonpark** [comment]
(각 repository가 아닌 각 folder를 말씀하시는 것이죠?)
네, `gshs_thesis_xxxx`형태로 남기면 좋을 것 같습니다.

**Comment by seungwonpark** [comment]
@WoolSeo 선생님께서 2017학년도에 과학영재부에 계실 것이라는 말씀을 들었던 것 같은데... 혹시 2017학년도에 졸업논문 양식이 변경될 계획이 있나요?

**Comment by EC97B0EAB79C** [comment]
`gshs_thesis`가 2015이고 `gshs_thesis-adv`가 2016인가요?

**Comment by seungwonpark** [comment]
`gshs_thesis`와 `gshs_thesis-adv`가 각각 2015, 2016이라고 볼 수 있겠지만, 원래는 `gshs_thesis-adv`가 텍을 능숙하게 다룰 수 있는 사용자들을 위한 양식이고, `gshs_thesis`가 텍을 처음 사용하는 초보자들을 위한 양식입니다.

때문에 폴더 명을 변경한다면 gshs_thesis_2015와 gshs_thesis_2016 정도로 변경하는 것이 가능하겠지만, 초보자들에는 2015가 더 사용하기 쉬운 양식이라는 점 정도를 안내하면 좋을 것 같습니다.

**Comment by seungwonpark** [comment]
들리는 소식에 의하면 이번 학기 들어서 과학영재부에서 송죽학사에 졸업논문 텍 양식을 목진욱 박사님이 제작하신 2015.11.13 버전으로 업로드했다고 하는군요. 그 버전은 현재의 `gshs_thesis`와는 다른, 오래된 버전입니다. 2015.11.13 버전으로부터 오타 수정, 한글/워드 양식과 글자크기 설정 등을 통일시키기 위해 많은 노력을 하여 `gshs_thesis`를 제작하였는데, 송죽학사에 아직도 2015.11.13 버전이 올라와 있는 것은 약간 유감스럽더군요...

2015.11.13 버전으로부터 `gshs_thesis`의 tex, cls파일이 어떻게 바뀌었는지는 https://git.io/vSvmi 와 https://git.io/vSvmP 처럼 Blame을 누르면 보실 수 있습니다.
