### ISSUE TITLE
Limit of document length

### ISSUE THREAD

**Issue by seungwonpark** [gshslatexintro/gshslatexintro#3]
gshslatexintro는 모든 사람들을 위한, 특히 경기과학고 학생을 위한 LaTeX 입문서입니다.
그런데 그 입문서이 길이가 너무 길어져 버린다면 "요약본"으로서의 의미를 상실하게 됩니다.
어떻게 해야 할까요?

**Comment by evenharder** [comment]
입문서가 요약본이 되어야 할 필요는 없지만, 입문서에 필요한 개념의 적다고 할 수는 없습니다. Python Tutorial(https://docs.python.org/3.4/tutorial/) 이 한 예시가 될 수 있습니다.

물론 이 글은 TeX의 입문서가 아니라, R&E를 할 때 참고할 만한 팁을 모아둔 것으로 보는 것이 조금 더 합당하겠지요. 근데 사실 어떠한 개념이 입문용이고 어떤 것은 조금 복잡한 개념인지 이를 구분하는 것은 쉽지 않을 것 같습니다.

아니면 pdf 파일을 여러 개 만드는 수도 있는데, 이는 일단 contibutor가 더 많아져야 생각할 문제일 것 같네요.

**Comment by seungwonpark** [comment]
(반영됨)
