### ISSUE TITLE
그래프 그리기

### ISSUE THREAD

**Issue by seungwonpark** [gshslatexintro/gshslatexintro#4]
우리가 흔히 보는 논문들은 엑셀 그래프가 아니라, gnuplot이나 LaTeX 내장함수에 의해 그려진 그래프인 듯 합니다. 배우고 싶다...
구글 검색하면 이에 관해 설명하는 문서들이 몇몇 있긴 합니다.
ex. https://tobi.oetiker.ch/lshort/lshort.pdf

**Comment by isty2e** [comment]
박사과정 대학원생입니다. 실제로 현업(?)에서는 Origin을 쓰는 사람이 한 무더기 있고, ggplot이나 matplotlib을 많이 씁니다. 또 저널마다 그림 스타일이 다르기 때문에 그에 맞춰 Adobe Illustrator 등으로 수정하는 경우도 꽤 있죠(예를 들어 Nature 등).

반면 그래프가 아닌 그림은 간단한 거라면 tikz로 그리는 게 일반적이구요.

**Comment by seungwonpark** [comment]
조언에 감사드립니다.
An Introduction to LaTeX 에 그래프 첨부 관련하여 가이드를 더 추가해야 할것 같군요.
선배님의 조언 + 제 경험 을 토대로 정리하면 

# 그래프 그리기
- Origin
- ggplot
- matplotlib
- gnuplot
  # 그림 넣기
- Adobe Illustrator
- tikz
- GeoGebra + tikz

**Comment by seungwonpark** [comment]
@LeeJuchan 여기요
