### ISSUE TITLE
Problem with labeling theorems

### ISSUE THREAD

**Issue by evenharder** [gshslatexintro/gshslatexintro#7]
자꾸 \begin{theorem} 등을 하면 Labeling이 1.0.1, 1.0.2의 형식으로 진행이 되서 조금 보기 그런데, 이를 class 파일에서 직접적으로 고치거나 할 수 있나요? 아니면 간접적으로 저 0의 index를 없앨 수 있나요?

**Comment by seungwonpark** [comment]
제가 theorem을 잘 안써봐서.. 원래는 어떻게 나와야 하나요?

**Comment by isty2e** [comment]
Chapter가 없고 Section 단위로 문서를 나눈 것 같군요. 이럴 때는 다음과 같이 처리하면 해결됩니다.

\newtheorem{theorem}{Theorem}[section]
\renewcommand{\thetheorem}{\arabic{section}.\arabic{theorem}}

renewcommand 부분에서 숫자를 arabic으로 할지 roman으로 할지 등등은 적절히 선택하시면 되고, \thetheorem 부분을 \newtheorem으로 정의한 theorem에 맞게 바꾸면 됩니다.

수정:

엄밀히 말해, 이것은 버그는 아닙니다. 그냥 chapter가 없고 section으로 나누고 하다 보면 원래 이렇게 되는 것이지, style에 문제가 있는 것은 아니거든요. 굳이 말하자면 좀 불편하거나 불합리한 점이라고 할 수 있겠지요.

**Comment by seungwonpark** [comment]
문제가 발생하는 근본적인 원인(chapter-section-subsection 체제)을 해결하였기 때문에,
해결되었을 것이라 간주하고 issue 를 닫습니다.
(현재 section-subsection-subsubsection 체제를 사용중)
