### ISSUE TITLE
Humantech sample .tex file is missing

### ISSUE THREAD

**Issue by isty2e** [gshslatexintro/gshslatexintro#8]
휴먼테크 .cls 파일은 올라와 있는데, 그에 맞는 적절한 샘플 .tex 파일이 없네요.

혼자서 .cls 파일 보면서 만들어 보려 했지만 아무래도 서식에 맞지 않는 부분이 있습니다. 샘플 .tex 파일도 같이 올려 주실 수 있으신가요?

**Comment by seungwonpark** [comment]
깜빡 잊고 안 올렸었네요. 샘플 tex 파일을 올려드렸습니다.
